[package]
name = "midnight-circuits"
version = "6.0.0"
edition = "2021"
license-file = "../LICENSE"
description = "Circuit and gadget implementations for Midnight zero-knowledge proofs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
group = "0.13"
ff = "0.13"
rustc-hash = "2"
midnight-curves = "0.2.0"
midnight-proofs = { version = "0.7.0", default-features = false, features = [
    "circuit-params",
    "committed-instances",
] }

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
sha2 = { version = "0.10.9" }
rand = { version = "0.8" }

num-bigint = { version = "0.4" }
num-traits = "0.2"
num-integer = "0.1"
subtle = "2.6"
base64 = "0.13.1"
lazy_static = "1.5.0"
goldenfile = { version = "=1.8.0", optional = true }
rand_chacha = { version = "0.3.1", optional = true }

[dev-dependencies]
criterion = "0.7"
rand_chacha = "0.3.1"
goldenfile = "=1.8.0"
num-bigint = { version = "0.4", features = ["rand"] }
serde_json = { version = "1" }
itertools = "0.14"
dhat = "0.3"

[target.'cfg(ci_build)'.dependencies]
midnight-curves = { version = "0.2.0", features = [
    "portable",
] }

[features]
default = []
# Feature that exposes some testing functionality, such as load from scratch or instantiable
testing = ["num-bigint/rand", "goldenfile", "serde_json", "rand_chacha"]
heap_profiling = []
# Enable truncated challenges. This makes recursive proofs more efficient
truncated-challenges = ["midnight-proofs/truncated-challenges"]
# Enable development curves (BN256, Pasta)
dev-curves = ["midnight-curves/dev-curves", "midnight-proofs/dev-curves"]

[lib]
bench = false

[[bench]]
name = "poseidon_cpu"
harness = false
